appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
provider: {win: azure}
travis:
  secure: {BINSTAR_TOKEN: PSjvrhGcfJeNeyKOE+p/efQl1ETUEj9z0ehR56rkMTnqcTFJBzqaf/qSUDKJyoVq9npwKxh9Udo8YR5vHdFUJ7PTTQwKJmcwOM8LZSU+1AT8COQNUrpwHxfj2ooYhQIeM6kyGVwW3h2ZA8YHAznnMCvq0h2P/lf4Hc+XFko28f3mc3rUBfvkYR1782kGeqUsXjxZa/DuVlNS2VKzdskt0IxOAizm0zbMyVRrSiQLu8yiDbSKoCUAND7af96DnJEiwpbM7IxqRWye2lz78RuYIK4scHh2HH/TSVSCXasRvMryr+L+2DGL0zHX/xhyAQklT0HTqjniSIXRh/f5yoSdlPu+2fVIU18311WcpNRxLK+qOfD5vYE6RNGTdD6gnYP9qIej0MF4Rbx9hY8WtM0tSc+3R5OMadAxHzQrh65gVsZxaR6luYkLyP/7iFfecskFdktMc3sgF/pHG6EaS41IvVSvVNg1hG3L6+egghOMojS3OR64vmchC+iF38rPg3NSAi4UaVpPTDNSdr97dLc1aCvezH45GmpV0/9fXSp65QxUznaWhQUg95bsOtqzzYLFqID5SwQA90TAJSlTQsZQn1px1SaVH4xvxI3Z1gj8QSxM2PkgC/E2L3BjI760RA4ZU3VQMxRDeiI3QjgNkZZxpXx7whWOTMGrt9hRo2nAkcU=}
bot:
  automerge: true
